// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var cheerio, fetch, parseDescription, parseImage, parseSitename, parseTitle, request;

  cheerio = require('cheerio');

  request = require('koa-request');

  fetch = function*(url) {
    var options;
    options = {
      url: url,
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36 scrapingjs(0.0.1)'
      }
    };
    return (yield request(options));
  };

  parseTitle = function($) {
    var title;
    title = $('title').text();
    if (!title) {
      title = $('h1').eq(0).text();
    }
    return title;
  };

  parseDescription = function($) {
    var description;
    description = $('meta[name="description"]').attr('content');
    if (!description) {
      description = $('meta[property="og:description"]').attr('content');
    }
    return description;
  };

  parseImage = function($) {
    var ogimage;
    ogimage = $('meta[property="og:image"]').attr('content');
    if (!ogimage) {
      ogimage = $('img').eq(0).attr('src');
    }
    return ogimage;
  };

  parseSitename = function($) {
    var sitename;
    sitename = $('meta[property="og:site_name"]').attr('content');
    return sitename;
  };

  module.exports.scrape = function*(url) {
    var $, res, response;
    response = (yield fetch(url));
    $ = cheerio.load(response.body);
    res = {
      title: parseTitle($),
      description: parseDescription($),
      thumbnail_url: parseImage($),
      sitename: parseSitename($),
      url: response.request.uri.href
    };
    return res;
  };

}).call(this);
