// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var client, parseDescription, parseImage, parseSitename, parseTitle;

  client = require('cheerio-httpcli');

  parseTitle = function($) {
    var title;
    title = $('title').text();
    if (!title) {
      title = $('h1').eq(0).text();
    }
    return title;
  };

  parseDescription = function($) {
    var description;
    description = $('meta[name="description"]').attr('content');
    if (!description) {
      description = $('meta[property="og:description"]').attr('content');
    }
    return description;
  };

  parseImage = function($, uri) {
    var ogimage;
    ogimage = $('meta[property="og:image"]').attr('content');
    return ogimage;
  };

  parseSitename = function($) {
    var sitename;
    sitename = $('meta[property="og:site_name"]').attr('content');
    return sitename;
  };

  module.exports.scrape = function*(url) {
    var $, res, result;
    result = (yield client.fetch(url, {}));
    $ = result.$;
    res = {
      title: parseTitle($),
      description: parseDescription($),
      thumbnail_url: parseImage($, result.response.request.uri),
      sitename: parseSitename($),
      url: result.response.request.uri.href
    };
    return res;
  };

}).call(this);
